server:
    port: 8888
spring:
    output:
        ansi:
            enabled: always
    profiles:
        active: local

at:
    primary-server: activetick1.activetick.com
    second-server: activetick2.activetick.com
    port: 443
    userid: {USERID}
    apikey: {APIKEY}
    password: {PASSWORD}

marketapi:
    pubsubBind: tcp://127.0.0.1:5678
